name: Java CI
on:
  pull_request:
    types: [edited, opened, reopened]
    branches:
      - 'feature/**'
jobs:
  gradle:
    runs-on: ubuntu-latest

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The name of your branch is ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "Setup JDK 11"
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin
      - name: Setup and execute Gradle 'runTests' task
        uses: gradle/gradle-build-action@v2
          with:
            arguments: runTests
      - run: echo "This job's status is ${{ job.status }}."