name: Pull requests runs
on:
  pull_request:
    types: [ edited, opened, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The name of the branch is ${{ github.ref }}"
      - run: echo "Check out repository code for ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v3

      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "Setup JDK 17"
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
      - run: echo "Run chmod to make gradlew executable"
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - run: echo "This job's status is ${{ job.status }}."
