name: Pull requests runs
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The name of the branch is ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: |
          ./gradlew clean test -Dos=unix

      - name: Publish TestNG Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: testng-reports
          path: build/reports/tests/testng
